# Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: dart_client
version: 0.3.0
description: A sample application serving a Dart web client.
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  appengine: ^0.7.0
  gcloud: ^0.6.0+4
  http_server: ^0.9.8+1

dev_dependencies:
  build_runner: ^1.5.0
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
